### PR TITLE
Add list-ops exercise

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by robkeim** [comment]
@ErikSchierboom - since folding is likely a foreign concept for those that aren't familiar with functional programming, could you add a HINTS.md?

I don't have a great tutorial, but the Wikipedia page isn't a bad start:
https://en.wikipedia.org/wiki/Fold_(higher-order_function)

**Comment by ErikSchierboom** [comment]
Doh! Very good point. I will add a hints file.

By the way, it's great that you so actively review my PR's! Feels good to share the work.

**Comment by robkeim** [comment]
You're welcome :)

**Comment by ErikSchierboom** [comment]
@robkeim I've added a HINTS.md file containing information on folds.

**Comment by robkeim** [comment]
Looks great, thanks @ErikSchierboom!

**Pull request merged**
