### PR TITLE
Add rotational-cipher exericse

### LINKED ISSUE #292: Implement Rotational Cipher exercise
The new exercise description and test cases can be found here:
https://github.com/exercism/x-common/tree/master/exercises/rotational-cipher

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Closes #292

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@robkeim Are you settled enough that you are ready to look at PR's? If not, no worries of course.

**Comment by robkeim** [comment]
@ErikSchierboom thanks for asking, I'm getting settled in now and will start looking through PRs more regularly.

**Comment by ErikSchierboom** [comment]
@robkeim Great! If you find you have a bit of spare time, I'd love to talk to you on what you think about the test generators. Let me know when you have some time :)

**Comment by robkeim** [comment]
@ErikSchierboom yes let's definitely chat! What's your preferred mechanism of communication among the myriad of options we have in today's high tech world? :)

**Comment by ErikSchierboom** [comment]
@robkeim I think a private chat on Gitter would be great.

**Comment by robkeim** [comment]
Sounds good @ErikSchierboom. I just sent you a message so we can find a time that works for both of us.

**Pull request merged**
