### PR TITLE
Add HINTS.md to diamond exercise

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Refs #209

### CODE REVIEW

**Comment by robkeim** [comment]
I just had a change to skim through your article looks really nice @ErikSchierboom! How do we handle the circleci failure? Do we merge anyway since this change couldn't have broken anything?

**Comment by ErikSchierboom** [comment]
@robkeim Yes please. The build failures is something that we have to deal with for a little while I think, until we get the Cake build working perfectly. For now, we can merge things.

**Comment by ErikSchierboom** [comment]
@robkeim By the way, I thought it a bit cheeky at first to link to my own blog post, so I tried to find a better one but failed :(

**Comment by robkeim** [comment]
@ErikSchierboom at first I was thinking it was a bit egoistic as well, but then I looked through and saw the detail and quality and I totally support you promoting your blog :)

**Comment by ErikSchierboom** [comment]
@robkeim :) If you do find a better link, feel free to replace mine or add it. All of the good explanations I found used F#.

**Comment by robkeim** [comment]
@ErikSchierboom maybe I'll have to make my own to compete with yours ;)

**Comment by ErikSchierboom** [comment]
:)

**Pull request merged**
