### PR TITLE
Move exercises into folder. Closes #46

### LINKED ISSUE #46: Move exercises to subdirectory
The problems api (x-api) now supports having exercises collected in a subdirectory
named `exercises`.

That is to say that instead of having a mix of `bin`, `docs`, and individual exercises,
we can have `bin`, `docs`, and `exercises` in the root of the repository, and all
the exercises collected in a subdirectory.

In other words, instead of this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── bowling
│   ├── bowling_test.ext
│   └── example.ext
├── clock
│   ├── clock_test.ext
│   └── example.ext
├── config.json
└── docs
│   ├── ABOUT.md
│   └── img
... etc
```

we can have something like this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── config.json
├── docs
│   ├── ABOUT.md
│   └── img
├── exercises
│   ├── bowling
│   │   ├── bowling_test.ext
│   │   └── example.ext
│   └── clock
│       ├── clock_test.ext
│       └── example.ext
... etc
```

This has already been deployed to production, so it's safe to make this change whenever you have time.

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by jwood803** [comment]
Whoops! Should I have done this first?

**Comment by ErikSchierboom** [comment]
@jwood803 No you shouldn't have, this is fine. I'll rebase this.

**Comment by ErikSchierboom** [comment]
@jwood803 There is some newline issue with the largest series product file. I'll look into it later.

**Comment by ErikSchierboom** [comment]
@jwood803 I fixed the newline issue. It is now ready to be merged I think.

**Comment by ErikSchierboom** [comment]
@jwood803 Could you take a look at this? Or perhaps I can also be added as a contributor? :angel:

**Comment by ErikSchierboom** [comment]
@jwood803 Great!

**Pull request merged**
