### PR TITLE
Bank account with threads

### PR DESCRIPTION
**Pull request by artiom**
Exercise mentions that solution should be thread safe [1]. However, there are no tests to verify that potential solution is thread safe.

Changes:
* Adjusted example implementation to be thread safe
* Added test with threads that is failing with previous implementation

[1] https://github.com/exercism/x-common/blob/master/exercises/bank-account/description.md
> Create an account that can be accessed from multiple threads/processes

### CODE REVIEW

**Comment by artiom** [comment]
Travis CI fails on unrelated issue to this PR and I can't find "rerun" button anywhere in their interface.

**Comment by ErikSchierboom** [comment]
LGTM! Thanks a lot. The failing Travis build is something that happens once in a while. As the AppVeyor build succeeds, this can be merged. :tada:

**Comment by ErikSchierboom** [comment]
I don't have access to a physical machine on the moment, which means I can't merge PR's with a failing status. To have Travis rebuild the PR, could you add a spaceshuttle somewhere and amend the commit?

**Comment by artiom** [comment]
@ErikSchierboom worked this time.

**Pull request merged**
