### PR TITLE
poker: straight to 5 in ascending order in example

### PR DESCRIPTION
**Pull request by rpottsoh**
While working with this exercise in Delphi it seemed to me that straight to 5 should be in descending order in the example.  I learned that all the tests would pass regardless if straight to 5 was ascending or descending.  I added a test that showed that ascending didn't work, descending does.  Hopefully I have found something here.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@rpottsoh Unfortunately, the code you submitted in this PR does not compile. At a quick glance, I found several errors:

- `Pokder.BestHands` should be `Poker.BestHands`
- `new{} { straightTo5` should be `new[] { straightTo5`

Also, `[Ignore("Remove torun test")]` should be `[Ignore("Remove to run test")]`

As for the actual issue, I'm not entirely sure what you mean. In the original test, there is one straight to 5 test:

```c#
const string straightTo1 = "AS QH KS TD JH";
const string straightTo5 = "4S AH 3S 2D 5H";
Assert.That(Poker.BestHands(new[] { straightTo1, straightTo5 }), Is.EqualTo(new[] { straightTo1 }));
```

Is there something wrong with this test?

**Comment by rpottsoh** [comment]
@ErikSchierboom I apologize for committing broken code.  I am not really setup for C# and I was in dire need of sleep when I posted this PR.  I should have grabbed some ZZs before posting.

I see nothing wrong with this test for what it is testing.

`const string straightTo1 = "AS QH KS TD JH";`
`const string straightTo5 = "4S AH 3S 2D 5H";`
`Assert.That(Poker.BestHands(new[] { straightTo1, straightTo5 }), Is.EqualTo(new[] { straightTo1 }));`

However, I think the test runner is missing a test where a straight to the 5 is the best hand.

In example.cs

`if (ranks.SequenceEqual(new[] { 14, 5, 4, 3, 2 }))`
`        {`
`            ranks = new[] { 1, 2, 3, 4, 5 };`
`        }`

When the original (raw) descending straight to 5 pattern is overwritten by the 1 to 5 ascending pattern the check for `straight` will not be correct.

`var straight = ranks.Distinct().Count() == 5 && ranks[0] - ranks[4] == 4;`

`ranks[0] - ranks[4] != 4` -4 instead. 

A new test of best hands with a best hand being a straight to 5 I think will fail.

My intent is not be critical of the example solution, but to mainly point out there is a test case that should be added.

I will clean up what I have committed.

**Comment by ErikSchierboom** [comment]
@rpottsoh Thanks's for taking the time explaining! This looks good. Great that you wanted to help us. 🎉

**Comment by rpottsoh** [comment]
No problem, glad to help.

**Pull request merged**
