### PR TITLE
Update sum of multiples test

### PR DESCRIPTION
**Pull request by duffn**
- Add the missing sum of multiples test. Addresses https://github.com/exercism/todo/issues/52
- Remove the NUnit Ignore attribute from the other tests.

### CODE REVIEW

**Comment by kytrinyx** [comment]
I'm curious about the `Ignore` attribute thing (I haven't been following the C# track closely). Is there a different issue open somewhere that says to not have the ignore directives?

Would you mind splitting this into two different pull requests? I can comfortably merge the one that adds the test (with an ignore directive), but I'm not sure about removing ignore directives, since it addresses a different problem and I've not been a part of the discussion about that.

**Comment by bressain** [comment]
I was under the impression that tests should be ignored until people are ready to continue on. Did this change?

**Comment by kytrinyx** [comment]
@bressain ah, you would have heard about it if so. I don't think so.

@duffn The ignore directives are there on purpose for all but the first test in order to simulate test driven development. If the C# test runner has a "fail fast" mode and a way to run the tests in the order specified, then we could lean on that, but otherwise I would prefer to leave them in place unless there's a good argument for removing them.

**Comment by duffn** [comment]
@kytrinyx I see, that makes sense. I will update.

**Comment by duffn** [comment]
Closed in favor of PR without removing the Ignore attributes. https://github.com/exercism/xcsharp/pull/41

**Comment by kytrinyx** [comment]
Cool, thanks.

**Pull request closed without merging**
