### PR TITLE
largest-series-product corner cases

### PR DESCRIPTION
**Pull request by petertseng**
As part of the work to have consistency between tracks as in https://github.com/exercism/todo/issues/104 and https://github.com/exercism/todo/issues/13. Comments are in individual commit messages.

### CODE REVIEW

**Comment by kytrinyx** [comment]
I'm not sure who's around these days who knows C#. @jwood803 do you know C#? I think I keep asking this. If the answer is yes, would it be OK if I add you as a maintainer on this track? There aren't pull requests very often.

I guess maybe @joce or @ronnieoverby might have an opinion (I see that you both have commented on the C# track on Exercism fairly recently).

**Comment by jwood803** [comment]
Yep, I'm mainly a C# dev. And I'll do my best as a maintainer :}

**Comment by kytrinyx** [comment]
w00t! Thank you!

**Comment by joce** [comment]
Humm? What can I do for you?

**Comment by jwood803** [comment]
Changes look good to me. I'll merge this in. :shipit:

**Comment by kytrinyx** [comment]
@joce I was hoping you could review the code so I could merge it, but @jwood803 took care of it. Thanks y'all.

**Pull request merged**
