### PR TITLE
Add Minesweeper exercise

### PR DESCRIPTION
**Pull request by robkeim**

### CODE REVIEW

**Comment by robkeim** [comment]
My config changes weren't correct, I'll create a new PR.

**Comment by kytrinyx** [comment]
@robkeim :heart:

As a side note, you can `git push --force` to your branch if you want to rebase or amend commits or whatever and then have that reflected in your pull request.

**Comment by robkeim** [comment]
Thanks Kytrinyx for the feedback, it's much appreciated!

I though it was never a good idea to go a `git push --force` due to the fact that remote branches could already be in use. I guess in this case it's a near zero probability since it's my own fork that I'm modifying where I'm the only contributor.

**Comment by kytrinyx** [comment]
Yeah, in the case of pull requests I push --force all the time. If I'm collaborating with people I sometimes do, but only if I've discussed with everyone ahead of time.

**Comment by robkeim** [comment]
Alright I'll keep that in mind for next time, thanks again for the tips!

**Comment by robkeim** [comment]
Alright I'll keep that in mind for next time, thanks again for the tips!

**Comment by robkeim** [comment]
Alright I'll keep that in mind for next time, thanks again for the tips!

**Pull request closed without merging**
