### PR TITLE
Add link to NUnit Test Adapter for Visual Studio into readme

### PR DESCRIPTION
**Pull request by robkeim**
Adding a note about VS 2012/2013 compatibility with NUnit as requested in issue #45.

### CODE REVIEW

**Comment by robkeim** [comment]
@ErikSchierboom any advice on this error? I couldn't get a repro on my local machine.

```
System.Exception: Start of process C:\Tools\NUnit3\bin\nunit3-console.exe failed. The system cannot find the file specified
   at Fake.ProcessHelper.ExecProcessWithLambdas@79-16.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 79
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 79
   at Fake.Testing.NUnit3.NUnit3(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\NUnit\NUnit3.fs:line 280
   at FSI_0005.Build.clo@41-9.Invoke(Unit _arg5) in C:\projects\xcsharp\build.fsx:line 43
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492
```

**Comment by ErikSchierboom** [comment]
@robkeim That must be something like a race condition, it has nothing to do with your PR. Thanks for the contribution! 🎉

**Comment by robkeim** [comment]
Good to know. In the future if something happens like that for a code related change is there a way to restart the tests or do you have to submit a new PR or iteration to the PR?

**Comment by ErikSchierboom** [comment]
Well, you can't re-run the builds that are automatically started, as @kytrinyx is the owner of the Travis and AppVeyor account referencing them. However, you can create an account at Travis and AppVeyor and have them automatically build your fork (that contains your PR).

**Pull request merged**
