### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by ErikSchierboom**
- Use Paket for dependency management
- Normalize test file names
- Fix not all tests being run

### CODE REVIEW

**Comment by kytrinyx** [comment]
Is this catching existing test failures?

**Comment by ErikSchierboom** [comment]
Yes it is. There is still a bug somewhere, but when it's done it will automatically run all tests using the example code.

**Comment by kytrinyx** [comment]
OK cool. How do you feel about merging this with a failing build? That always makes me super nervous, but on the other hand it's already broken, this is just finally saying so.

**Comment by ErikSchierboom** [comment]
I will only merge this once it's working again. This is basically a work in progress.

**Pull request merged**
